
const API_CONSULTAS_RECLAMOS = "https://script.google.com/macros/s/AKfycbzcbjCLweJNgZXDerdzmMN7Lwotc1G8NWdzoPkaLNGDivAgpYxDkq78xZwPRioSB4XY/exec";
async function crApi(payload){const r=await fetch(API_CONSULTAS_RECLAMOS,{method:"POST",body:JSON.stringify(payload)});const d=await r.json();if(!d.ok)throw new Error(d.error||"Error en Consultas y Reclamos");return d;}
function crEsc(v){return String(v??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[m]));}
function crPerfil(){return (localStorage.getItem("perfil")||"").toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");}
function crCategorias(){return {
 "BONO, PRODUCCION Y PUNTAJE":["PUNTOS NO CONTABILIZADOS","BONO INCORRECTO","TRABAJO MAL REGISTRADO"],
 "DEMORA O FALTA DE RESPUESTA DE BACK":["BACK NO RESPONDE","DEMORA EXCESIVA","NO RESPONDE EN EL GRUPO"],
 "SUPERVISOR":["SUPERVISOR NO RESPONDE","DEMORA EN VALIDACION","FALTA DE APOYO OPERATIVO"],
 "CLIENTE REVISITADO":["VISITADO POR OTRA CONTRATA","CLIENTE MOLESTO","TRABAJO ANTERIOR INCOMPLETO"],
 "ALMACEN":["FALTA DE EQUIPOS","FALTA DE MATERIALES","SERIES O ENTREGAS","ACTAS O DOCUMENTACION","DEMORA DE ATENCION"],
 "OTRO CASO OPERATIVO":["OTRO"]};}
function mostrarConsultasReclamos(){limpiarPantalla();const menu=document.getElementById("menuPrincipal");if(menu)menu.style.setProperty("display","none","important");setBotonNavegacion("modulo");const p=document.getElementById("pantalla"),cats=crCategorias();p.innerHTML=`<div class="cr-wrap"><div class="cr-title">💬 CONSULTAS Y RECLAMOS</div><div class="cr-tabs"><button onclick="crMostrarSeccion('lista')">Mis casos</button><button onclick="crMostrarSeccion('nuevo')">Registrar caso</button></div><section id="crNuevo" class="cr-panel" style="display:none"><h3>Registrar consulta o reclamo</h3><div class="cr-grid"><label>Categoría<select id="crCategoria" onchange="crActualizarSubcategoria()"><option value="">SELECCIONE</option>${Object.keys(cats).map(x=>`<option>${x}</option>`).join("")}</select></label><label>Subcategoría<select id="crSubcategoria"><option value="">SELECCIONE</option></select></label><label>Urgencia<select id="crUrgencia"><option>NORMAL</option><option>URGENTE</option></select></label><label>Código de pedido<input id="crCodigo" placeholder="Opcional"></label><label>Ticket<input id="crTicket" placeholder="Opcional"></label><label>Cliente<input id="crCliente" placeholder="Opcional"></label></div><label>Descripción<textarea id="crDescripcion" rows="5" placeholder="Explique claramente lo ocurrido"></textarea></label><label>Evidencias o enlaces<textarea id="crEvidencias" rows="2" placeholder="Pegue enlaces de capturas, fotos o documentos"></textarea></label><button class="cr-primary" onclick="crRegistrar()">Registrar caso</button><div id="crMsg"></div></section><section id="crLista" class="cr-panel"><div id="crResumen" class="cr-resumen"></div><div class="cr-filtros"><select id="crFiltroEstado" onchange="crCargar()"><option value="">TODOS LOS ESTADOS</option><option>REGISTRADO</option><option>EN REVISION</option><option>EN PROCESO</option><option>PENDIENTE DE INFORMACION</option><option>SOLUCIONADO</option><option>CERRADO</option></select><select id="crFiltroArea" onchange="crCargar()"><option value="">TODAS LAS AREAS</option><option>JEFATURA GENERAL</option><option>JEFATURA DE OPERACIONES</option><option>JEFATURA DE ALMACEN</option></select></div><div id="crCasos">Cargando...</div></section></div>`;window.scrollTo({top:0,behavior:"smooth"});crCargar();}
function crMostrarSeccion(s){document.getElementById("crNuevo").style.display=s==="nuevo"?"block":"none";document.getElementById("crLista").style.display=s==="lista"?"block":"none";if(s==="lista")crCargar();}
function crActualizarSubcategoria(){const c=document.getElementById("crCategoria").value,l=crCategorias()[c]||[],s=document.getElementById("crSubcategoria");s.innerHTML='<option value="">SELECCIONE</option>'+l.map(x=>`<option>${x}</option>`).join("");}
async function crRegistrar(){const msg=document.getElementById("crMsg");msg.textContent="Registrando...";try{const d=await crApi({accion:"registrarConsultaReclamo",usuario:localStorage.getItem("usuario"),categoria:crCategoria.value,subcategoria:crSubcategoria.value,urgencia:crUrgencia.value,codigoPedido:crCodigo.value,ticket:crTicket.value,cliente:crCliente.value,descripcion:crDescripcion.value,evidencias:crEvidencias.value});msg.innerHTML=`<b>Caso ${crEsc(d.id)} registrado y derivado a ${crEsc(d.areaResponsable)}.</b>`;[crCodigo,crTicket,crCliente,crDescripcion,crEvidencias].forEach(x=>x.value="");}catch(e){msg.textContent=e.message;}}
async function crCargar(){const box=document.getElementById("crCasos");if(!box)return;box.textContent="Cargando casos...";try{const d=await crApi({accion:"listarConsultasReclamos",usuario:localStorage.getItem("usuario"),estado:crFiltroEstado?.value||"",area:crFiltroArea?.value||""});const r=d.resumen;document.getElementById("crResumen").innerHTML=`<div><b>${r.total}</b><span>Total</span></div><div><b>${r.registrados}</b><span>Registrados</span></div><div><b>${r.enProceso+r.enRevision}</b><span>En atención</span></div><div><b>${r.pendienteInformacion}</b><span>Pendiente info.</span></div><div><b>${r.solucionados}</b><span>Solucionados</span></div>`;box.innerHTML=d.casos.length?d.casos.map(x=>`<article class="cr-card ${x.urgencia==='URGENTE'?'cr-urgente':''}"><div class="cr-card-head"><b>${crEsc(x.id)} · ${crEsc(x.categoria)}</b><span>${crEsc(x.estado)}</span></div><div class="cr-meta">${crEsc(x.sede)} · ${crEsc(x.cuadrilla||x.tecnico)} · ${crEsc(x.areaResponsable)}</div><p>${crEsc(x.descripcion)}</p><button onclick="crDetalle('${crEsc(x.id)}')">Ver detalle</button></article>`).join(""):'<div class="cr-empty">No hay casos para este filtro.</div>';}catch(e){box.textContent=e.message;}}
async function crDetalle(id){try{const d=await crApi({accion:"listarConsultasReclamos",usuario:localStorage.getItem("usuario")}),x=d.casos.find(c=>c.id===id);if(!x)return;const h=await crApi({accion:"listarHistorialReclamo",usuario:localStorage.getItem("usuario"),id});const p=crPerfil(),areaPerfil=d.areaPerfil||"",puede=(areaPerfil&&areaPerfil===x.areaResponsable)||(p.includes("JEFATURA")&&x.areaResponsable==="JEFATURA GENERAL")||(x.tecnico===localStorage.getItem("usuario")&&x.estado==="SOLUCIONADO");document.getElementById("crCasos").innerHTML=`<button onclick="crCargar()">← Volver</button><article class="cr-detail"><h3>${crEsc(x.id)} — ${crEsc(x.subcategoria)}</h3><div class="cr-detail-grid"><div><b>Área</b><br>${crEsc(x.areaResponsable)}</div><div><b>Estado</b><br>${crEsc(x.estado)}</div><div><b>Sede</b><br>${crEsc(x.sede)}</div><div><b>Cuadrilla</b><br>${crEsc(x.cuadrilla)}</div><div><b>Código</b><br>${crEsc(x.codigoPedido||'-')}</div><div><b>Ticket</b><br>${crEsc(x.ticket||'-')}</div></div><h4>Descripción</h4><p>${crEsc(x.descripcion)}</p>${x.evidencias?`<h4>Evidencias</h4><p>${crEsc(x.evidencias)}</p>`:''}<h4>Historial</h4><div class="cr-history">${h.historial.map(y=>`<div><b>${crEsc(y.accion)} · ${crEsc(y.usuario)}</b><br>${crEsc(y.comentario||'')}<small>${crEsc(y.estadoAnterior)} → ${crEsc(y.estadoNuevo)}</small></div>`).join('')}</div><textarea id="crComentario" rows="3" placeholder="Comentario o respuesta"></textarea><div class="cr-actions"><button onclick="crComentar('${id}')">Agregar comentario</button>${puede?`<select id="crNuevoEstado"><option>EN REVISION</option><option>EN PROCESO</option><option>PENDIENTE DE INFORMACION</option><option>SOLUCIONADO</option><option>RECHAZADO</option><option>CERRADO</option></select><button class="cr-primary" onclick="crActualizar('${id}')">Guardar estado</button>`:''}</div></article>`;}catch(e){alert(e.message);}}
async function crComentar(id){try{await crApi({accion:"agregarComentarioReclamo",usuario:localStorage.getItem("usuario"),id,comentario:crComentario.value});crDetalle(id);}catch(e){alert(e.message);}}
async function crActualizar(id){try{await crApi({accion:"actualizarConsultaReclamo",usuario:localStorage.getItem("usuario"),id,estado:crNuevoEstado.value,comentario:crComentario.value});crDetalle(id);}catch(e){alert(e.message);}}
window.mostrarConsultasReclamos=mostrarConsultasReclamos;
