/* ============================================================
   MI VISUAL V380 - Facturas de Combustible
   Carga perezosa. Fotos se comprimen en navegador antes de enviar.
============================================================ */
(function(){
"use strict";
const API=()=>window.MI_VISUAL_API_URL||"https://script.google.com/macros/s/AKfycbwugGpuEMcJYFsDNS1hkcdZXJ92PUvXNv5ttpktyhZWv2fWB7ceCZNkfIFYxAs5wsgN/exec";
const U=()=>localStorage.getItem("usuario")||"";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let CTX=null,DET=null,filas=0;
async function get(accion,extra={}){const u=new URL(API());u.searchParams.set("accion",accion);u.searchParams.set("usuario",U());Object.entries(extra).forEach(([k,v])=>{if(v!==undefined&&v!==null)u.searchParams.set(k,v)});u.searchParams.set("_",Date.now());const r=await fetch(u.toString(),{cache:"no-store"});const t=await r.text();let j;try{j=JSON.parse(t)}catch(_){throw new Error("La respuesta de Apps Script no es JSON válido")};if(!r.ok||j.ok===false)throw new Error(j.error||"No se pudo completar la consulta");return j;}
async function post(accion,data={}){const r=await fetch(API(),{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({accion,usuario:U(),...data})});const t=await r.text();let j;try{j=JSON.parse(t)}catch(_){throw new Error("La respuesta de Apps Script no es JSON válido")};if(!r.ok||j.ok===false)throw new Error(j.error||"No se pudo completar la operación");return j;}
function pantalla(html){if(typeof window.limpiarPantalla==="function")window.limpiarPantalla();const m=document.getElementById("menuPrincipal");if(m)m.style.setProperty("display","none","important");if(typeof window.setBotonNavegacion==="function")window.setBotonNavegacion("modulo");const p=document.getElementById("pantalla");if(p)p.innerHTML=html;window.scrollTo({top:0,behavior:"smooth"});}
function colorEstado(e){e=String(e||"").toUpperCase();return e==="APROBADO"?"ok":e==="OBSERVADO"?"obs":e==="PRESENTADO"?"pre":e==="VENCIDO"?"ven":"pen";}
function moneda(n){return `S/ ${Number(n||0).toFixed(2)}`;}
function renderResumen(r){return `<div class="mv380-kpis"><div><b>${r.pendientes||0}</b><span>Pendientes</span></div><div><b>${r.presentados||0}</b><span>Presentados</span></div><div><b>${r.observados||0}</b><span>Observados</span></div><div><b>${r.aprobados||0}</b><span>Aprobados</span></div><div><b>${r.vencidos||0}</b><span>Vencidos</span></div></div>`;}
function cardPend(x){return `<article class="mv380-pend-card"><div class="mv380-pend-top"><div><b>${esc(x.nombreResponsable)}</b><small>${esc(x.sede)} · ${esc(x.cuadrilla||x.perfilResponsable)}</small></div><span class="mv380-estado ${colorEstado(x.estadoVisible)}">${esc(x.estadoVisible)}</span></div><div class="mv380-pend-meta"><span>📅 ${esc(x.fechaDesde)} → ${esc(x.fechaHasta)}</span><span>🚗 ${esc(x.placa||"Sin placa")}</span><span>⛽ ${moneda(x.montoRequerido)}</span><span>🧾 ${x.cantidad||0} factura(s)</span></div>${x.observacion?`<div class="mv380-alerta">${esc(x.observacion)}</div>`:""}<button class="mv380-btn secondary" onclick="abrirPendienteFacturaV380('${esc(x.id)}')">Abrir detalle</button></article>`;}
function renderPrincipal(){
 const periodos=(CTX.periodos||[]).map(p=>`<option value="${esc(p)}" ${p===CTX.periodoMes?"selected":""}>${esc(p)}</option>`).join("");
 pantalla(`<div class="mv380-page"><header class="mv380-head"><span>⛽</span><div><h2>FACTURAS DE COMBUSTIBLE</h2><p>Sustento de comprobantes por periodo.</p></div></header>${renderResumen(CTX.resumen||{})}<div class="mv380-toolbar"><label>Periodo mensual<select id="mv380Periodo" onchange="cambiarPeriodoFacturasV380(this.value)">${periodos}</select></label>${CTX.puedeCrear?'<button class="mv380-btn primary" onclick="abrirCrearPendienteV380()">＋ Crear pendiente</button>':""}</div><section class="mv380-lista">${(CTX.lista||[]).length?(CTX.lista||[]).map(cardPend).join(""):'<div class="mv380-vacio">No hay pendientes en este periodo.</div>'}</section></div>`);
}
window.mostrarFacturas=async function(){pantalla('<div class="mv380-cargando">⏳ Cargando Facturas...</div>');try{CTX=await get("obtenerContextoFacturas");renderPrincipal()}catch(e){pantalla(`<div class="mv380-error"><b>No se pudo abrir Facturas</b><span>${esc(e.message)}</span><button class="mv380-btn primary" onclick="mostrarFacturas()">Reintentar</button></div>`);}};
window.cambiarPeriodoFacturasV380=async function(p){pantalla('<div class="mv380-cargando">⏳ Consultando periodo...</div>');try{CTX=await get("obtenerContextoFacturas",{periodoMes:p});renderPrincipal()}catch(e){alert(e.message)}};
window.abrirCrearPendienteV380=function(){if(!CTX||!CTX.puedeCrear)return;const ops=(CTX.responsables||[]).map((x,i)=>`<option value="${esc(x.usuario)}" data-i="${i}">${esc(x.nombre)} · ${esc(x.perfil)} · ${esc(x.sede)}</option>`).join("");pantalla(`<div class="mv380-page"><header class="mv380-head"><span>➕</span><div><h2>Crear pendiente</h2><p>Gerencia General define responsable y periodo.</p></div></header><div class="mv380-form"><label>Responsable<select id="mv380Resp" onchange="infoRespFacturasV380()"><option value="">Seleccione...</option>${ops}</select></label><div id="mv380InfoResp" class="mv380-info"></div><div class="mv380-dos"><label>Desde<input type="date" id="mv380Desde"></label><label>Hasta<input type="date" id="mv380Hasta"></label></div><label>Monto requerido<input value="${Number(CTX.configuracion.monto).toFixed(2)}" readonly></label><label>Observación opcional<textarea id="mv380Obs" rows="2"></textarea></label><div class="mv380-actions"><button class="mv380-btn primary" onclick="crearPendienteFacturasV380()">Crear pendiente</button><button class="mv380-btn secondary" onclick="mostrarFacturas()">Cancelar</button></div></div></div>`);};
window.infoRespFacturasV380=function(){const s=document.getElementById("mv380Resp"),d=document.getElementById("mv380InfoResp");if(!s||!d)return;const x=(CTX.responsables||[])[Number(s.selectedOptions[0]?.dataset.i)];d.innerHTML=x?`🚗 <b>${esc(x.placa||"Sin placa")}</b> · Frecuencia: <b>${x.frecuencia?`cada ${x.frecuencia} días`:"sin definir"}</b> · ${esc(x.cuadrilla||"")}`:"";};
window.crearPendienteFacturasV380=async function(){const resp=document.getElementById("mv380Resp")?.value,desde=document.getElementById("mv380Desde")?.value,hasta=document.getElementById("mv380Hasta")?.value,observacion=document.getElementById("mv380Obs")?.value||"";if(!resp||!desde||!hasta)return alert("Seleccione responsable y periodo");try{const j=await post("crearPendienteFactura",{usuarioResponsable:resp,fechaDesde:desde,fechaHasta:hasta,observacion});alert(`${j.mensaje}\n${j.periodo}`);return mostrarFacturas()}catch(e){alert(e.message)}};
window.abrirPendienteFacturaV380=async function(id){pantalla('<div class="mv380-cargando">⏳ Abriendo detalle...</div>');try{DET=await get("obtenerDetalleFactura",{id});renderDetalle()}catch(e){alert(e.message);mostrarFacturas()}};
function detalleCard(d){return `<div class="mv380-detalle ${colorEstado(d.estado)}"><div><b>${esc(d.numero)}</b><small>${moneda(d.monto)} · ${esc(d.estado)}</small>${d.observacion?`<em>${esc(d.observacion)}</em>`:""}</div>${d.url?`<a href="${esc(d.url)}" target="_blank" rel="noopener">Ver foto</a>`:""}${DET.puedeValidar&&d.estado==="PRESENTADO"?`<button class="mv380-mini danger" onclick="observarFacturaV380('${esc(d.id)}')">Observar</button>`:""}</div>`;}
function renderDetalle(){const p=DET.pendiente,det=DET.detalles||[];const obs=det.filter(d=>d.estado==="OBSERVADO");let carga="";if(DET.puedeCargar&&(p.estado==="PENDIENTE"||p.estadoVisible==="VENCIDO")){filas=0;carga=`<section class="mv380-carga"><h3>Subir comprobantes</h3><p>Ingrese número, monto y fotografía. El total debe ser exactamente <b>${moneda(p.montoRequerido)}</b>. Máximo ${DET.configuracion.maxFacturas} fotos.</p><div id="mv380Filas"></div><div class="mv380-total">Total: <b id="mv380Total">S/ 0.00</b> / ${moneda(p.montoRequerido)}</div><button class="mv380-btn primary" onclick="presentarFacturasV380()">Presentar facturas</button></section>`;}else if(DET.puedeCargar&&p.estado==="OBSERVADO"&&obs.length){carga=`<section class="mv380-carga"><h3>Reemplazar facturas observadas</h3><p>Solo debe reemplazar los comprobantes marcados como observados.</p><div id="mv380Filas">${obs.map((d,i)=>filaHtml(i+1,d.id,d.numero,d.monto)).join("")}</div><div class="mv380-total">Total final debe quedar en <b>${moneda(p.montoRequerido)}</b></div><button class="mv380-btn primary" onclick="presentarFacturasV380(true)">Enviar reemplazos</button></section>`;filas=obs.length;}
 const aprobar=DET.puedeValidar&&p.estado==="PRESENTADO"?`<button class="mv380-btn success" onclick="aprobarFacturasV380('${esc(p.id)}')">✅ Aprobar presentación</button>`:"";
 pantalla(`<div class="mv380-page"><header class="mv380-head"><span>🧾</span><div><h2>${esc(p.nombreResponsable)}</h2><p>${esc(p.fechaDesde)} al ${esc(p.fechaHasta)} · ${esc(p.sede)}</p></div></header><div class="mv380-resumen-det"><span>Estado <b class="mv380-estado ${colorEstado(p.estadoVisible)}">${esc(p.estadoVisible)}</b></span><span>Monto <b>${moneda(p.montoRequerido)}</b></span><span>Placa <b>${esc(p.placa||"Sin placa")}</b></span><span>Frecuencia <b>${p.frecuencia?`cada ${p.frecuencia} días`:"sin definir"}</b></span></div><section><h3>Comprobantes</h3>${det.length?det.map(detalleCard).join(""):'<div class="mv380-vacio">Aún no hay comprobantes.</div>'}</section>${carga}<div class="mv380-actions">${aprobar}<button class="mv380-btn secondary" onclick="mostrarFacturas()">Volver</button></div></div>`);if(carga&&!obs.length)setTimeout(()=>agregarFilaFacturaV380(),0);}
function filaHtml(n,reemplazaId="",numero="",monto=""){return `<div class="mv380-fila" data-reemplaza="${esc(reemplazaId)}"><div class="mv380-num">Factura ${n}</div>${reemplazaId?`<small>Reemplaza: ${esc(numero)} · ${moneda(monto)}</small>`:""}<div class="mv380-tres"><label>Número<input class="mv380-f-num" maxlength="40" placeholder="Ej. F001-25874"></label><label>Monto<input class="mv380-f-monto" type="number" min="0.01" step="0.01" oninput="actualizarTotalFacturasV380()"></label><label>Foto<input class="mv380-f-file" type="file" accept="image/*" onchange="fotoFacturaSeleccionadaV380(this)"></label></div><div class="mv380-preview"></div></div>`;}
window.agregarFilaFacturaV380=function(){if(!DET||filas>=Number(DET.configuracion.maxFacturas))return;filas++;document.getElementById("mv380Filas")?.insertAdjacentHTML("beforeend",filaHtml(filas));};
window.fotoFacturaSeleccionadaV380=function(input){const fila=input.closest(".mv380-fila"),prev=fila?.querySelector(".mv380-preview");if(prev)prev.textContent=input.files?.[0]?.name?`📷 ${input.files[0].name}`:"";const todas=[...document.querySelectorAll(".mv380-fila")];if(!fila?.dataset.reemplaza&&fila===todas[todas.length-1]&&input.files?.[0])agregarFilaFacturaV380();};
window.actualizarTotalFacturasV380=function(){const t=[...document.querySelectorAll(".mv380-f-monto")].reduce((s,x)=>s+(Number(x.value)||0),0);const e=document.getElementById("mv380Total");if(e)e.textContent=moneda(t);};
async function comprimir(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onerror=()=>rej(new Error("No se pudo leer la imagen"));fr.onload=()=>{const img=new Image();img.onerror=()=>rej(new Error("Imagen no válida"));img.onload=()=>{const max=1280,escala=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.round(img.width*escala);c.height=Math.round(img.height*escala);c.getContext("2d").drawImage(img,0,0,c.width,c.height);const d=c.toDataURL("image/jpeg",.72);res({base64:d.split(",")[1],mime:"image/jpeg"});};img.src=fr.result;};fr.readAsDataURL(file);});}
window.presentarFacturasV380=async function(reemplazos=false){const fs=[...document.querySelectorAll(".mv380-fila")].filter(f=>f.querySelector(".mv380-f-num")?.value||f.querySelector(".mv380-f-monto")?.value||f.querySelector(".mv380-f-file")?.files?.[0]);if(!fs.length)return alert("Ingrese al menos una factura");const datos=[];let total=0;for(const f of fs){const numero=f.querySelector(".mv380-f-num").value.trim().toUpperCase(),monto=Number(f.querySelector(".mv380-f-monto").value),file=f.querySelector(".mv380-f-file").files?.[0];if(!numero||!monto||!file)return alert("Cada factura necesita número, monto y fotografía");if(!/^[A-Z0-9][A-Z0-9.\-\/]{1,39}$/.test(numero))return alert(`Número de factura inválido: ${numero}`);total+=monto;const img=await comprimir(file);datos.push({numero,monto,...img,reemplazaId:f.dataset.reemplaza||""});}
 if(!reemplazos&&Math.abs(total-Number(DET.pendiente.montoRequerido))>.009)return alert(`La suma debe ser exactamente ${moneda(DET.pendiente.montoRequerido)}. Actualmente: ${moneda(total)}`);
 const btn=(document.activeElement&&document.activeElement.classList&&document.activeElement.classList.contains("mv380-btn"))?document.activeElement:null;if(btn){btn.disabled=true;btn.textContent="Guardando..."}try{const j=await post("presentarFacturas",{id:DET.pendiente.id,facturas:datos});alert(j.mensaje);return abrirPendienteFacturaV380(DET.pendiente.id)}catch(e){alert(e.message);if(btn){btn.disabled=false;btn.textContent=reemplazos?"Enviar reemplazos":"Presentar facturas"}}};
window.observarFacturaV380=async function(id){const motivo=prompt("Indique el motivo de observación de esta factura:");if(!motivo)return;try{await post("observarDetalleFactura",{idDetalle:id,observacion:motivo});return abrirPendienteFacturaV380(DET.pendiente.id)}catch(e){alert(e.message)}};
window.aprobarFacturasV380=async function(id){if(!confirm("¿Aprobar toda la presentación de facturas?"))return;try{const j=await post("aprobarPresentacionFacturas",{id});alert(j.mensaje);return abrirPendienteFacturaV380(id)}catch(e){alert(e.message)}};
})();