/* MI VISUAL V363 - MI DESEMPEÑO para Técnico */
(function(){
  "use strict";
  function n(v){const x=Number(v);return Number.isFinite(x)?x:0;}
  function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
  function card(icono,titulo,valor,sub,onclick,color){return `<button type="button" onclick="${onclick}" style="text-align:left;border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:15px;background:${color||'#142844'};color:#fff;cursor:pointer"><div style="font-size:12px;color:#c8d8ed;font-weight:900">${icono} ${esc(titulo)}</div><div style="font-size:25px;font-weight:900;margin-top:7px">${valor}</div><div style="font-size:11px;color:#9fb7d8;margin-top:5px">${esc(sub||'')}</div></button>`;}
  async function mostrar(periodo){mostrarPantalla(`<div style="padding:20px;color:#fff"><h2>📊 MI DESEMPEÑO</h2>Cargando indicadores...</div>`);try{const data=await mv361ConsultarResumenDashboardRanking(periodo,false);const x=(data.lista||[])[0]||{};const d=x.mv353CumplimientoDia||{};const meta=n(d.metaAcumulada),puntos=n(x.produccion),cumpl=meta>0?puntos/meta*100:0;const sla=window.mv363SemaforoSla?mv363SemaforoSla(x.slaAjustado):{icono:''};mostrarPantalla(`<div style="padding:18px;max-width:900px;margin:auto;color:#fff"><h2>📊 MI DESEMPEÑO</h2><div style="margin:12px 0"><select onchange="mostrarMiDesempeno(this.value)" style="width:100%;padding:11px;border-radius:10px">${(data.periodos||[]).map(p=>`<option value="${esc(p.clave)}" ${p.clave===data.periodo?'selected':''}>${esc(p.etiqueta)}</option>`).join('')}</select></div><div style="padding:16px;border-radius:18px;background:linear-gradient(135deg,#0f172a,#1d4ed8);margin-bottom:12px"><div style="font-size:12px;color:#bfdbfe;font-weight:900">MI META AL DÍA</div><div style="font-size:31px;font-weight:900;margin-top:6px">${cumpl.toFixed(1)}%</div><div style="margin-top:5px">${puntos.toFixed(1)} de ${meta.toFixed(1)} puntos esperados</div><div style="font-size:11px;color:#bfdbfe;margin-top:4px">${n(d.diasCampo)} días en campo × ${n(d.metaDiaria||5)} puntos</div></div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px">${card('📈','Producción',`${puntos.toFixed(1)} pts`,`${cumpl.toFixed(1)}% de la meta al día`,`mostrarProduccionV2('${esc(data.periodo)}')`,'#164e63')}${card('🎯','Efectividad',`${n(x.efectividad).toFixed(1)}%`,'Ver detalle actual',`mostrarEfectividad('${esc(data.periodo)}')`,'#065f46')}${card('🔧','Recableado',`${n(x.recableado).toFixed(1)}%`,'Ver detalle actual',`mostrarRecableado('${esc(data.periodo)}')`,'#9a3412')}${card('📡','VTR / GAR',`${n(x.vtrgar).toFixed(1)}%`,'Ver detalle actual',`mostrarVTRGAR('${esc(data.periodo)}')`,'#a16207')}${card('⏱️','Tiempo de Gestión - SLA',`${n(x.slaAjustado).toFixed(1)}% ${sla.icono||''}`,`Bruto ${n(x.slaBruto).toFixed(1)}% · ${n(x.detSla?.evaluables)} códigos`,`mostrarTiempoGestionSla('${esc(data.periodo)}')`,'#3730a3')}${card('🏆','Ranking',x.puestoRegion?`#${x.puestoRegion}`:'Sin posición',`Puntaje ${n(x.puntaje).toFixed(2)}`,`mostrarRanking('${esc(data.periodo)}')`,'#6d28d9')}</div><br><button class="button_1" onclick="volverInicio()">⬅️ Volver al menú</button></div>`);}catch(e){mostrarPantalla(`<div style="padding:20px"><h2>📊 MI DESEMPEÑO</h2>❌ ${esc(e.message)}<br><br><button class="button_1" onclick="volverInicio()">⬅️ Volver</button></div>`);}}
  window.mostrarMiDesempeno=mostrar;
})();
