// MI VISUAL V156 - Permisos dinámicos por perfil
const API_PERMISOS = "https://script.google.com/macros/s/AKfycbzcbjCLweJNgZXDerdzmMN7Lwotc1G8NWdzoPkaLNGDivAgpYxDkq78xZwPRioSB4XY/exec";
let PM_PERMISOS = null;
function pmNorm(v){return (v||"").toString().toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim();}
async function pmApi(payload){const r=await fetch(API_PERMISOS,{method:'POST',body:JSON.stringify(payload)});const d=await r.json();if(!d.ok)throw new Error(d.error||'Error de permisos');return d;}
async function pmCargarPermisosActuales(forzar){if(PM_PERMISOS&&!forzar)return PM_PERMISOS;const usuario=localStorage.getItem('usuario')||'';if(!usuario)return [];try{const d=await pmApi({accion:'obtenerPermisosUsuario',usuario});PM_PERMISOS=d.permisos||[];localStorage.setItem('permisosModulos',JSON.stringify(PM_PERMISOS));return PM_PERMISOS;}catch(e){console.warn('Permisos: se conserva configuración anterior',e);try{PM_PERMISOS=JSON.parse(localStorage.getItem('permisosModulos')||'null');}catch(_){PM_PERMISOS=null;}return PM_PERMISOS||[];}}
function pmFila(modulo){const m=pmNorm(modulo);return (PM_PERMISOS||[]).find(x=>pmNorm(x.modulo)===m&&pmNorm(x.activo||'SI')==='SI');}
function pmPuede(modulo,accion){if(!PM_PERMISOS)return true;const f=pmFila(modulo);if(!f)return false;return pmNorm(f[accion.toLowerCase()]||f[accion]||'NO')==='SI';}
function pmModulosMenu(){if(!PM_PERMISOS)return null;return PM_PERMISOS.filter(x=>pmNorm(x.activo||'SI')==='SI'&&pmNorm(x.mostrarModulo||'NO')==='SI'&&pmNorm(x.ver||'NO')==='SI').sort((a,b)=>(Number(a.ordenMenu)||999)-(Number(b.ordenMenu)||999));}
const PM_CARD_MAP={'PRODUCCION':'cardProduccion','EFECTIVIDAD':'cardEfectividad','PORCENTAJE RECABLEADO':'cardRecableado','VTR GAR':'cardVTRGAR','RANKING':'cardRanking','OBSERVACIONES':'cardObservaciones','ACCESOS':'cardAccesos','BIBLIOTECA':'cardBiblioteca','CAPACITACION':'cardCapacitacion','DASHBOARD SUPERVISOR':'cardDashboardSupervisor','DASHBOARD JEFATURA':'cardDashboardJefatura','ANALISIS ECONOMICO':'cardAnalisisEconomico','ACTIVIDAD CAMPO':'cardActividadCampo','VALIDACION TECNICA':'cardValidacionTecnica','ACTAS ESCANEADAS':'cardActas','CHECKLIST ALMACEN':'cardChecklistAlmacen','PROGRAMACION DESCANSOS':'cardProgramacionDescansos','PEXT':'cardTrabajosConjunta','ADMINISTRACION':'cardAdministracion'};
function pmPanelAdmin(){return `<div class="adm104-config"><div class="pm-admin"><h3>🔐 Permisos por perfil</h3><p>Configura módulos, acciones, alcance y vista sin alterar las funciones actuales.</p><div class="pm-grid"><label>Perfil<input id="pmPerfil" list="pmPerfiles" placeholder="Ej. OPERACIONES LIMA"><datalist id="pmPerfiles"></datalist></label><label>Módulo<select id="pmModulo"></select></label><label>Activo<select id="pmActivo"><option>SI</option><option>NO</option></select></label><label>Orden menú<input id="pmOrden" type="number" min="1"></label><label>Mostrar módulo<select id="pmMostrar"><option>SI</option><option>NO</option></select></label><label>Alcance<select id="pmAlcance"><option>SIN ACCESO</option><option>CUADRILLA</option><option>SEDE</option><option>SEDE / PROPIOS</option><option>ZONA NORTE</option><option>PERSONAL</option><option>SEGUN DESTINO</option></select></label></div><div id="pmChecks" class="pm-checks"></div><label class="pm-obs">Observación<textarea id="pmObs"></textarea></label><div class="pm-actions"><button class="button_1" onclick="pmCargarFilaAdmin()">Consultar</button><button class="button_1" onclick="pmGuardarAdmin()">Guardar permiso</button></div><div id="pmMsg"></div></div></div>`;}
async function pmInitAdmin(){try{const d=await pmApi({accion:'listarPermisosAdministracion',usuario:localStorage.getItem('usuario')});window.PM_ADMIN=d.permisos||[];const perfiles=[...new Set(PM_ADMIN.map(x=>x.perfil))].sort();document.getElementById('pmPerfiles').innerHTML=perfiles.map(x=>`<option value="${x}">`).join('');const mods=[...new Set(PM_ADMIN.map(x=>x.modulo))];document.getElementById('pmModulo').innerHTML=mods.map(x=>`<option>${x}</option>`).join('');document.getElementById('pmChecks').innerHTML=['VER','REGISTRAR','EDITAR','OBSERVAR','APROBAR','VALIDAR','DESCARGAR','ADMINISTRAR'].map(x=>`<label><input type="checkbox" data-pm="${x}"> ${x}</label>`).join('');}catch(e){document.getElementById('pmMsg').textContent=e.message;}}
function pmCargarFilaAdmin(){const p=pmNorm(document.getElementById('pmPerfil').value),m=pmNorm(document.getElementById('pmModulo').value),f=(window.PM_ADMIN||[]).find(x=>pmNorm(x.perfil)===p&&pmNorm(x.modulo)===m);if(!f)return alert('No existe esa combinación. Puede crearla y guardarla.');document.getElementById('pmActivo').value=f.activo||'SI';document.getElementById('pmOrden').value=f.ordenMenu||'';document.getElementById('pmMostrar').value=f.mostrarModulo||'NO';document.getElementById('pmAlcance').value=f.alcanceDatos||'SIN ACCESO';document.getElementById('pmObs').value=f.observacion||'';document.querySelectorAll('[data-pm]').forEach(c=>c.checked=pmNorm(f[c.dataset.pm.toLowerCase()]||'NO')==='SI');}
async function pmGuardarAdmin(){const payload={accion:'guardarPermisoModulo',usuario:localStorage.getItem('usuario'),perfil:document.getElementById('pmPerfil').value,modulo:document.getElementById('pmModulo').value,activo:document.getElementById('pmActivo').value,ordenMenu:document.getElementById('pmOrden').value,mostrarModulo:document.getElementById('pmMostrar').value,alcanceDatos:document.getElementById('pmAlcance').value,observacion:document.getElementById('pmObs').value};document.querySelectorAll('[data-pm]').forEach(c=>payload[c.dataset.pm.toLowerCase()]=c.checked?'SI':'NO');try{await pmApi(payload);document.getElementById('pmMsg').innerHTML='<b style="color:#16a34a">Permiso guardado.</b>';await pmInitAdmin();}catch(e){document.getElementById('pmMsg').textContent=e.message;}}
