// MI VISUAL - Registro de Trabajos en Conjunta v151
const API_TRABAJOS_CONJUNTA = "https://script.google.com/macros/s/AKfycbzcbjCLweJNgZXDerdzmMN7Lwotc1G8NWdzoPkaLNGDivAgpYxDkq78xZwPRioSB4XY/exec";
let tcRegistros = [];
let tcCuadrillas = [];

function tcUsuario(){return {usuario:localStorage.getItem("usuario")||"",perfil:(localStorage.getItem("perfil")||"").toUpperCase(),sede:localStorage.getItem("sede")||"",cuadrilla:localStorage.getItem("cuadrilla")||""};}
function tcJefatura(p){return ["JEFATURA","ADMIN","ADMINISTRADOR"].includes((p||"").toUpperCase());}
async function tcApi(payload){const r=await fetch(API_TRABAJOS_CONJUNTA,{method:"POST",body:JSON.stringify(payload)});const t=await r.text();let d;try{d=JSON.parse(t)}catch(e){throw new Error(t)}if(!d.ok)throw new Error(d.error||"Error en Trabajos en Conjunta");return d;}
function tcEsc(v){return (v??"").toString().replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function tcFmtFecha(v){if(!v)return "-";if(v instanceof Date)return v.toLocaleDateString("es-PE");const s=v.toString();return /^\d{4}-\d{2}-\d{2}$/.test(s)?s.split("-").reverse().join("/"):s;}
function tcLoading(txt){let o=document.getElementById("tcLoading");if(!o){o=document.createElement("div");o.id="tcLoading";o.className="tc-loading";o.innerHTML='<div><span class="tc-spin"></span><b id="tcLoadingTxt">Procesando...</b></div>';document.body.appendChild(o)}document.getElementById("tcLoadingTxt").textContent=txt||"Procesando...";o.style.display="flex";}
function tcLoadingOff(){const o=document.getElementById("tcLoading");if(o)o.style.display="none";}

function mostrarTrabajosConjunta(){
  const u=tcUsuario();
  limpiarPantalla();setBotonNavegacion("modulo");
  const pantalla=document.getElementById("pantalla");
  pantalla.innerHTML=`${tcEstilos()}<div class="tc-wrap">
    <section class="tc-head"><h2>🤝 Trabajos en Conjunta</h2><p>Registro, visto bueno técnico y conformidad de Jefatura.</p></section>
    <div class="tc-actions">${u.perfil==="SUPERVISOR"?'<button class="tc-btn" onclick="tcMostrarFormulario()">＋ Nuevo registro</button>':''}<button class="tc-btn tc-sec" onclick="tcCargar()">↻ Actualizar</button></div>
    <section id="tcFormulario"></section>
    <section class="tc-card"><h3>Consulta de registros</h3><div class="tc-filtros">
      <select id="tcFiltroTipo" onchange="tcRenderLista()"><option value="">Todos los tipos</option><option>NORMALIZACION</option><option>CONJUNTA PEXT</option><option>ORDENAMIENTO</option></select>
      <select id="tcFiltroEstado" onchange="tcRenderLista()"><option value="">Todos los estados</option><option>PENDIENTE DE VISTO BUENO TECNICO</option><option>OBSERVADO POR TECNICO</option><option>PENDIENTE DE VALIDACION JEFATURA</option><option>PENDIENTE CONFORMIDAD FINAL</option><option>CONFORMIDAD FINAL</option><option>OBSERVADO POR JEFATURA</option><option>RECHAZADO</option></select>
      <input id="tcFiltroCuadrilla" placeholder="Buscar cuadrilla" oninput="tcRenderLista()">
      <input id="tcFiltroDesde" type="date" onchange="tcRenderLista()"><input id="tcFiltroHasta" type="date" onchange="tcRenderLista()">
    </div><div id="tcResumen"></div><div id="tcLista" class="tc-lista"></div></section>
  </div>`;
  tcCargar();
}

async function tcCargar(){try{tcLoading("Cargando trabajos...");const u=tcUsuario();const d=await tcApi({accion:"listarTrabajosConjunta",usuario:u.usuario});tcRegistros=d.trabajos||[];if(u.perfil==="SUPERVISOR"){const q=await tcApi({accion:"listarCuadrillasTrabajosConjunta",usuario:u.usuario});tcCuadrillas=q.cuadrillas||[];}tcRenderLista();}catch(e){document.getElementById("tcLista").innerHTML=`<div class="tc-error">${tcEsc(e.message)}</div>`;}finally{tcLoadingOff();}}

function tcMostrarFormulario(){
 const hoy=new Date().toISOString().slice(0,10);const opts=tcCuadrillas.map(x=>`<option value="${tcEsc(x.cuadrilla)}">${tcEsc(x.cuadrilla)}</option>`).join("");
 document.getElementById("tcFormulario").innerHTML=`<section class="tc-card tc-form"><h3>Nuevo trabajo en conjunta</h3><div class="tc-grid">
 <label>Cuadrilla<select id="tcCuadrilla"><option value="">Seleccione</option>${opts}</select></label>
 <label>Tipo de trabajo<select id="tcTipo" onchange="tcTipoCambio()"><option value="">Seleccione</option><option>NORMALIZACION</option><option>CONJUNTA PEXT</option><option>ORDENAMIENTO</option></select></label>
 <label>Fecha<input id="tcFecha" type="date" value="${hoy}"></label><label>Hora de inicio<input id="tcInicio" type="time"></label><label>Hora de fin<input id="tcFin" type="time"></label>
 </div><div id="tcCamposTipo"></div><div class="tc-grid"><label>Trabajos adicionales<textarea id="tcAdicionales" placeholder="Detalle de trabajos adicionales"></textarea></label><label>Puntos<input id="tcPuntos" type="number" min="0" step="0.01" value="0"></label><label class="tc-wide">Comentario final<textarea id="tcComentario" placeholder="Comentario final del registro"></textarea></label></div>
 <div class="tc-evidencias"><b>Evidencias (mínimo 1, máximo 3)</b><input id="tcEvidencias" type="file" accept="image/*" multiple></div>
 <div class="tc-actions"><button class="tc-btn tc-ok" onclick="tcGuardar(this)">Guardar y enviar al Técnico</button><button class="tc-btn tc-sec" onclick="document.getElementById('tcFormulario').innerHTML=''">Cancelar</button></div><div id="tcMsg"></div></section>`;
}
function tcTipoCambio(){const t=document.getElementById("tcTipo").value;let h="";if(t==="NORMALIZACION")h=`<div class="tc-grid"><label class="tc-wide">Descripción del trabajo<textarea id="tcDescripcion"></textarea></label></div>`;if(t==="CONJUNTA PEXT")h=`<div class="tc-grid"><label>CTO<input id="tcCto" placeholder="Ej. WN-12345"></label><label>Conectorizados - cantidad<input id="tcConCant" type="number" min="0" value="0" oninput="tcCodigosDinamicos('con')"></label><div id="tcCodCon" class="tc-wide"></div><label>Recableados - cantidad<input id="tcRecCant" type="number" min="0" value="0" oninput="tcCodigosDinamicos('rec')"></label><div id="tcCodRec" class="tc-wide"></div></div>`;if(t==="ORDENAMIENTO")h=`<div class="tc-grid"><label>Cantidad de cuadras intervenidas<input id="tcCuadras" type="number" min="1"></label><label>Zona o referencia<input id="tcZona"></label></div>`;document.getElementById("tcCamposTipo").innerHTML=h;}
function tcCodigosDinamicos(tipo){const esCon=tipo==="con",n=Math.max(0,parseInt(document.getElementById(esCon?"tcConCant":"tcRecCant").value)||0),id=esCon?"tcCodCon":"tcCodRec",pref=esCon?"Conectorizado":"Recableado";document.getElementById(id).innerHTML=n?`<div class="tc-codigos"><b>Códigos de ${pref}s</b>${Array.from({length:n},(_,i)=>`<input class="${esCon?'tcCodigoCon':'tcCodigoRec'}" placeholder="Código ${i+1}">`).join("")}</div>`:"";}
function tcArchivoBase64(file){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok({nombre:file.name,mime:file.type||"image/jpeg",base64:r.result.split(",")[1]});r.onerror=no;r.readAsDataURL(file);});}
async function tcGuardar(btn){const msg=document.getElementById("tcMsg");try{btn.disabled=true;tcLoading("Guardando registro...");const t=document.getElementById("tcTipo").value,files=[...(document.getElementById("tcEvidencias").files||[])];if(!files.length)throw new Error("Debe adjuntar al menos una evidencia");if(files.length>3)throw new Error("Máximo 3 evidencias");const evidencias=await Promise.all(files.map(tcArchivoBase64));const payload={accion:"registrarTrabajoConjunta",usuario:tcUsuario().usuario,cuadrilla:document.getElementById("tcCuadrilla").value,tipoTrabajo:t,fechaTrabajo:document.getElementById("tcFecha").value,horaInicio:document.getElementById("tcInicio").value,horaFin:document.getElementById("tcFin").value,trabajosAdicionales:document.getElementById("tcAdicionales").value,puntosSolicitados:document.getElementById("tcPuntos").value,comentarioFinal:document.getElementById("tcComentario").value,evidencias};if(t==="NORMALIZACION")payload.descripcionTrabajo=document.getElementById("tcDescripcion").value;if(t==="CONJUNTA PEXT"){payload.cto=document.getElementById("tcCto").value;payload.cantidadConectorizados=document.getElementById("tcConCant").value;payload.codigosConectorizados=[...document.querySelectorAll(".tcCodigoCon")].map(x=>x.value);payload.cantidadRecableados=document.getElementById("tcRecCant").value;payload.codigosRecableados=[...document.querySelectorAll(".tcCodigoRec")].map(x=>x.value);}if(t==="ORDENAMIENTO"){payload.cantidadCuadras=document.getElementById("tcCuadras").value;payload.zonaReferencia=document.getElementById("tcZona").value;}await tcApi(payload);msg.innerHTML='<div class="tc-okmsg">Registro guardado correctamente.</div>';document.getElementById("tcFormulario").innerHTML="";await tcCargar();}catch(e){msg.innerHTML=`<div class="tc-error">${tcEsc(e.message)}</div>`;}finally{btn.disabled=false;tcLoadingOff();}}

function tcRenderLista(){const tipo=(document.getElementById("tcFiltroTipo")?.value||""),estado=(document.getElementById("tcFiltroEstado")?.value||""),cuad=(document.getElementById("tcFiltroCuadrilla")?.value||"").toUpperCase(),desde=document.getElementById("tcFiltroDesde")?.value||"",hasta=document.getElementById("tcFiltroHasta")?.value||"";const arr=tcRegistros.filter(x=>(!tipo||x.tipoTrabajo===tipo)&&(!estado||x.estadoGeneral===estado)&&(!cuad||(x.cuadrilla||"").toUpperCase().includes(cuad))&&(!desde||x.fechaTrabajo>=desde)&&(!hasta||x.fechaTrabajo<=hasta));const r=document.getElementById("tcResumen");if(r)r.innerHTML=`<div class="tc-kpis"><div><b>${arr.length}</b><span>Total</span></div><div><b>${arr.filter(x=>x.estadoGeneral==="PENDIENTE DE VISTO BUENO TECNICO").length}</b><span>Pendiente Técnico</span></div><div><b>${arr.filter(x=>x.estadoGeneral==="PENDIENTE CONFORMIDAD FINAL").length}</b><span>Pendiente Jefatura</span></div><div><b>${arr.filter(x=>x.estadoGeneral==="CONFORMIDAD FINAL").length}</b><span>Conformes</span></div></div>`;const lista=document.getElementById("tcLista");if(!arr.length){lista.innerHTML='<div class="tc-vacio">No hay registros.</div>';return}lista.innerHTML=arr.map(tcTarjeta).join("");}
function tcTarjeta(x){const u=tcUsuario(),pendTec=x.estadoGeneral==="PENDIENTE DE VISTO BUENO TECNICO",pendJef=x.estadoGeneral==="PENDIENTE DE VALIDACION JEFATURA"||x.estadoGeneral==="OBSERVADO POR TECNICO",pendConf=x.estadoGeneral==="PENDIENTE CONFORMIDAD FINAL";let acc="";if(u.perfil==="TECNICO"&&pendTec)acc=`<button class="tc-btn tc-ok" onclick="tcRespuestaTecnico('${tcEsc(x.id)}','VISTO BUENO')">Visto bueno</button><button class="tc-btn tc-warn" onclick="tcRespuestaTecnico('${tcEsc(x.id)}','OBSERVADO')">Observar</button>`;if(tcJefatura(u.perfil)&&pendJef)acc=`<button class="tc-btn tc-ok" onclick="tcValidarJefatura('${tcEsc(x.id)}','APROBADO')">Aprobar</button><button class="tc-btn tc-warn" onclick="tcValidarJefatura('${tcEsc(x.id)}','OBSERVADO')">Observar</button><button class="tc-btn tc-danger" onclick="tcValidarJefatura('${tcEsc(x.id)}','RECHAZADO')">Rechazar</button>`;if(tcJefatura(u.perfil)&&pendConf)acc=`<button class="tc-btn tc-ok" onclick="tcConformidad('${tcEsc(x.id)}','CONFORME')">Dar conformidad final</button><button class="tc-btn tc-danger" onclick="tcConformidad('${tcEsc(x.id)}','SIN CONFORMIDAD')">Sin conformidad</button>`;return `<article class="tc-item"><div class="tc-item-top"><div><b>${tcEsc(x.cuadrilla)} · ${tcEsc(x.tipoTrabajo)}</b><small>${tcFmtFecha(x.fechaTrabajo)} · ${tcEsc(x.horaInicio)} a ${tcEsc(x.horaFin)} · ${tcEsc(x.supervisorRegistra)}</small></div><span class="tc-estado">${tcEsc(x.estadoGeneral)}</span></div><details><summary>Ver detalle</summary>${tcDetalle(x)}<div class="tc-actions">${acc}</div></details></article>`;}
function tcDetalle(x){return `<div class="tc-det"><p><b>Puntos:</b> ${tcEsc(x.puntosSolicitados)}</p>${x.descripcionTrabajo?`<p><b>Descripción:</b> ${tcEsc(x.descripcionTrabajo)}</p>`:""}${x.cto?`<p><b>CTO:</b> ${tcEsc(x.cto)}</p>`:""}${x.cantidadConectorizados!==""?`<p><b>Conectorizados:</b> ${tcEsc(x.cantidadConectorizados)} ${x.codigosConectorizados?`· ${tcEsc(x.codigosConectorizados)}`:""}</p>`:""}${x.cantidadRecableados!==""?`<p><b>Recableados:</b> ${tcEsc(x.cantidadRecableados)} ${x.codigosRecableados?`· ${tcEsc(x.codigosRecableados)}`:""}</p>`:""}${x.cantidadCuadras?`<p><b>Cuadras:</b> ${tcEsc(x.cantidadCuadras)} · ${tcEsc(x.zonaReferencia)}</p>`:""}<p><b>Adicionales:</b> ${tcEsc(x.trabajosAdicionales||"-")}</p><p><b>Comentario:</b> ${tcEsc(x.comentarioFinal||"-")}</p>${x.observacionTecnico?`<p><b>Observación Técnico:</b> ${tcEsc(x.observacionTecnico)}</p>`:""}${x.observacionJefatura?`<p><b>Observación Jefatura:</b> ${tcEsc(x.observacionJefatura)}</p>`:""}<p><b>Evidencias:</b> ${[x.evidencia1,x.evidencia2,x.evidencia3].filter(Boolean).map((l,i)=>`<a target="_blank" href="${tcEsc(l)}">Evidencia ${i+1}</a>`).join(" · ")||"-"}</p></div>`;}
async function tcRespuestaTecnico(id,res){const obs=res==="OBSERVADO"?prompt("Ingrese la observación obligatoria:"):"";if(res==="OBSERVADO"&&!obs)return;try{tcLoading("Guardando respuesta...");await tcApi({accion:"responderTrabajoConjuntaTecnico",usuario:tcUsuario().usuario,id,resultado:res,observacion:obs});await tcCargar();}catch(e){alert(e.message)}finally{tcLoadingOff();}}
async function tcValidarJefatura(id,res){const obs=res!=="APROBADO"?prompt("Ingrese el motivo obligatorio:"):prompt("Comentario de validación (opcional):")||"";if(res!=="APROBADO"&&!obs)return;try{tcLoading("Validando...");await tcApi({accion:"validarTrabajoConjuntaJefatura",usuario:tcUsuario().usuario,id,resultado:res,observacion:obs});await tcCargar();}catch(e){alert(e.message)}finally{tcLoadingOff();}}
async function tcConformidad(id,res){const obs=res==="SIN CONFORMIDAD"?prompt("Ingrese el motivo obligatorio:"):prompt("Comentario final de conformidad (opcional):")||"";if(res==="SIN CONFORMIDAD"&&!obs)return;try{tcLoading("Registrando conformidad...");await tcApi({accion:"conformidadFinalTrabajoConjunta",usuario:tcUsuario().usuario,id,resultado:res,observacion:obs});await tcCargar();}catch(e){alert(e.message)}finally{tcLoadingOff();}}
function tcEstilos(){return `<style>.tc-wrap{max-width:980px;margin:auto;padding:12px 12px 90px;color:#fff}.tc-head,.tc-card{background:#1d3557;border:1px solid #38577f;border-radius:18px;padding:17px;margin:12px 0;box-shadow:0 8px 22px #0003}.tc-head h2{margin:0 0 6px}.tc-head p{margin:0;color:#d5e5fa}.tc-actions{display:flex;gap:9px;flex-wrap:wrap;margin:12px 0}.tc-btn{border:0;border-radius:11px;padding:11px 14px;background:#087cf0;color:#fff;font-weight:800;cursor:pointer}.tc-sec{background:#475569}.tc-ok{background:#15803d}.tc-warn{background:#d97706}.tc-danger{background:#dc2626}.tc-grid,.tc-filtros{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.tc-filtros{grid-template-columns:repeat(3,minmax(0,1fr))}.tc-grid label{font-size:12px;font-weight:800;color:#f1f5f9;display:flex;flex-direction:column;gap:6px}.tc-grid input,.tc-grid select,.tc-grid textarea,.tc-filtros input,.tc-filtros select,.tc-evidencias input{width:100%;box-sizing:border-box;padding:11px;border-radius:10px;border:1px solid #5a779c;background:#fff;color:#111827;font-size:14px}.tc-grid textarea{min-height:80px}.tc-wide{grid-column:1/-1}.tc-evidencias{padding:12px;margin-top:12px;background:#12243e;border-radius:12px}.tc-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:13px 0}.tc-kpis div{background:#10243e;padding:12px;border-radius:12px;text-align:center}.tc-kpis b,.tc-kpis span{display:block}.tc-kpis b{font-size:22px}.tc-kpis span{font-size:11px;color:#cbd5e1}.tc-item{background:#f8fafc;color:#111827;border-radius:15px;padding:14px;margin:10px 0;border-left:6px solid #0ea5e9}.tc-item-top{display:flex;justify-content:space-between;gap:10px;align-items:center}.tc-item small{display:block;color:#475569;margin-top:4px}.tc-estado{font-size:11px;font-weight:900;background:#dbeafe;padding:7px 10px;border-radius:999px}.tc-item summary{cursor:pointer;font-weight:800;margin-top:10px}.tc-det{padding:8px 4px}.tc-det a{color:#0369a1;font-weight:800}.tc-error,.tc-okmsg,.tc-vacio{padding:13px;border-radius:12px;margin:9px 0}.tc-error{background:#7f1d1d;color:#fff}.tc-okmsg{background:#166534}.tc-vacio{background:#10243e;text-align:center}.tc-codigos{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;background:#10243e;padding:10px;border-radius:12px}.tc-codigos b{grid-column:1/-1}.tc-loading{display:none;position:fixed;inset:0;background:#0009;z-index:99999;align-items:center;justify-content:center}.tc-loading>div{background:#12243e;padding:20px;border-radius:16px;display:flex;gap:10px;align-items:center}.tc-spin{width:22px;height:22px;border:3px solid #fff4;border-top-color:#fff;border-radius:50%;animation:tcs .8s linear infinite}@keyframes tcs{to{transform:rotate(360deg)}}@media(max-width:700px){.tc-grid,.tc-filtros{grid-template-columns:1fr}.tc-kpis{grid-template-columns:repeat(2,1fr)}.tc-item-top{align-items:flex-start;flex-direction:column}.tc-codigos{grid-template-columns:1fr}}</style>`;}
