-- MI VISUAL — borrador inicial del piloto Mapa Operativo
-- NO EJECUTAR EN PRODUCCIÓN HASTA CREAR EL PROYECTO SUPABASE DE PRUEBAS.

create table if not exists public.ordenes (
  id bigint generated by default as identity primary key,
  orden_id text not null,
  tipo_trabajo text,
  grupo_trabajo text,
  fecha_solicitud date,
  hora_solicitud time without time zone,
  cliente text,
  tipo text,
  producto_origen text,
  cuadrilla text,
  estado text,
  direccion text,
  direccion_adicional text,
  fecha_ultimo_estado timestamp without time zone,
  producto_servicio text,
  sede text,
  codigo_cliente text,
  numero_documento text,
  telefono_movil text,
  telefono_fijo text,
  fecha_fin_visita timestamp without time zone,
  fecha_inicio_visita timestamp without time zone,
  motivo_cancelacion text,
  motivo_finalizacion text,
  motivo_anulacion text,
  latitud double precision,
  longitud double precision,
  detalle text,
  fecha_importacion timestamp without time zone,
  usuario_importacion text,
  cto_1 text,
  coordenada_cto_1 text,
  cto_2 text,
  coordenada_cto_2 text,
  cto_3 text,
  coordenada_cto_3 text,
  cto text,
  puerto text,
  codigo_seguimiento text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ordenes_orden_id_uk unique (orden_id)
);

create index if not exists ordenes_fecha_idx
  on public.ordenes (fecha_solicitud);

create index if not exists ordenes_sede_fecha_idx
  on public.ordenes (sede, fecha_solicitud);

create index if not exists ordenes_cuadrilla_fecha_idx
  on public.ordenes (cuadrilla, fecha_solicitud);

create index if not exists ordenes_estado_fecha_idx
  on public.ordenes (estado, fecha_solicitud);

create index if not exists ordenes_grupo_fecha_idx
  on public.ordenes (grupo_trabajo, fecha_solicitud);

create index if not exists ordenes_documento_idx
  on public.ordenes (numero_documento);

create index if not exists ordenes_cliente_idx
  on public.ordenes (codigo_cliente);

create index if not exists ordenes_seguimiento_idx
  on public.ordenes (codigo_seguimiento);

create index if not exists ordenes_lat_lng_idx
  on public.ordenes (latitud, longitud);

create table if not exists public.catalogo_cto (
  id bigint generated by default as identity primary key,
  codigo_cto text not null,
  latitud double precision,
  longitud double precision,
  coordenada text,
  sede text,
  primera_deteccion timestamp without time zone,
  ultima_actualizacion timestamp without time zone,
  orden_referencia text,
  codigo_cliente text,
  tipo_trabajo text,
  puerto_referencia text,
  usuario_actualizacion text,
  veces_detectada integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalogo_cto_codigo_uk unique (codigo_cto)
);

create index if not exists catalogo_cto_sede_idx
  on public.catalogo_cto (sede);

create index if not exists catalogo_cto_lat_lng_idx
  on public.catalogo_cto (latitud, longitud);

-- Nota:
-- RLS, roles y políticas NO se habilitan todavía en este borrador.
-- Se diseñarán antes de conectar el frontend de pruebas.
