'use strict';
const authClient=supabase.createClient('https://uudvodiaizfarodjpetb.supabase.co','sb_publishable_2hiwePKtqoo3_c_D5B9JuA_p38dPe3D');
const field=id=>document.getElementById(id);
let recoveryReady=false;
function showRecovery(){recoveryReady=true;sessionStorage.setItem('mv-recovery','1');field('request').hidden=true;field('change').hidden=false;field('status').textContent='Enlace validado. Introduce una contraseña de al menos 12 caracteres.';}
authClient.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY')showRecovery();if(event==='SIGNED_OUT'){recoveryReady=false;sessionStorage.removeItem('mv-recovery');field('change').hidden=true;field('request').hidden=false;}});
async function initialize(){const {data,error}=await authClient.auth.getSession();if(error){history.replaceState(null,'',location.pathname);field('status').textContent='El enlace no es válido o ha vencido. Solicita otro.';sessionStorage.removeItem('mv-recovery');return;}if(data.session&&sessionStorage.getItem('mv-recovery')==='1')showRecovery();}
field('requestForm').onsubmit=async e=>{e.preventDefault();field('send').disabled=true;field('status').textContent='Solicitando enlace…';try{const {error}=await authClient.auth.resetPasswordForEmail(field('email').value.trim(),{redirectTo:'https://mi-visual-piloto.netlify.app/recuperar.html'});if(error)throw error;field('status').textContent='Solicitud aceptada. Si el correo tiene una cuenta, recibirás el enlace. Revisa también spam.';}catch(e){field('status').textContent='No se pudo enviar el enlace: '+e.message;}finally{field('send').disabled=false;}};
field('changeForm').onsubmit=async e=>{e.preventDefault();if(!recoveryReady){field('status').textContent='Abre primero el enlace de recuperación recibido en tu correo.';return;}const password=field('newPassword').value;if(password.length<12||password!==field('repeatPassword').value){field('status').textContent='Las contraseñas deben coincidir y tener al menos 12 caracteres.';return;}field('save').disabled=true;try{const {error}=await authClient.auth.updateUser({password});if(error)throw error;field('newPassword').value='';field('repeatPassword').value='';sessionStorage.removeItem('mv-recovery');recoveryReady=false;await authClient.auth.signOut({scope:'local'});field('change').hidden=true;field('request').hidden=true;field('continue').hidden=false;field('status').textContent='Contraseña actualizada. Ya puedes ingresar a MI VISUAL.';}catch(e){field('newPassword').value='';field('repeatPassword').value='';field('status').textContent='No se pudo actualizar: '+e.message;}finally{field('save').disabled=false;}};
initialize();
