-- MI VISUAL migration: Auth administration audit
-- Safe/idempotent. Does not alter production Apps Script or Google Sheets.

begin;

create table if not exists public.auth_access_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_auth_user_id uuid,
  actor_usuario text,
  actor_perfil text,
  accion text not null,
  target_app_user_id bigint,
  target_usuario text,
  target_correo text,
  target_auth_user_id uuid,
  resultado text not null,
  detalle jsonb not null default '{}'::jsonb
);

create index if not exists auth_access_audit_created_at_idx
  on public.auth_access_audit (created_at desc);

create index if not exists auth_access_audit_target_usuario_idx
  on public.auth_access_audit (target_usuario);

alter table public.auth_access_audit enable row level security;

revoke all on table public.auth_access_audit from anon, authenticated;
revoke all on sequence public.auth_access_audit_id_seq from anon, authenticated;

commit;
