-- MI VISUAL - Produccion: capa base de migracion y conciliacion
-- Rama migracion-supabase. No modifica Apps Script, Google Sheets ni main.
-- Preserva datos legacy sin consolidar catalogos ambiguos.

begin;

create table if not exists public.catalogo_partidas_migracion (
  id bigint generated by default as identity primary key,
  source_row integer not null unique,
  codigo text not null,
  tipo_orden text,
  plataforma_orden text,
  puntaje numeric(12,3),
  grupo text,
  monto numeric(14,2),
  estado_tarifa text,
  imported_at timestamptz not null default now()
);

create index if not exists catalogo_partidas_migracion_codigo_idx
  on public.catalogo_partidas_migracion (upper(trim(codigo)));

create table if not exists public.produccion_legacy_snapshot (
  id text primary key,
  source_row integer not null unique,
  usuario text,
  cuadrilla text not null,
  fecha date not null,
  periodo text not null,
  codigo text not null,
  cantidad numeric(12,3) not null,
  fecha_actualizacion timestamp without time zone,
  source_name text not null default 'PRODUCCION_APP',
  imported_at timestamptz not null default now(),
  constraint produccion_legacy_cantidad_chk check (cantidad >= 0),
  constraint produccion_legacy_periodo_chk check (periodo ~ '^\d{4}-\d{2}$')
);

create index if not exists produccion_legacy_periodo_idx
  on public.produccion_legacy_snapshot (periodo);
create index if not exists produccion_legacy_cuadrilla_fecha_idx
  on public.produccion_legacy_snapshot (cuadrilla, fecha);
create index if not exists produccion_legacy_codigo_idx
  on public.produccion_legacy_snapshot (codigo);

create table if not exists public.base_operativa_legacy (
  id bigint generated by default as identity primary key,
  source_row integer not null unique,
  clave_registro text,
  periodo text,
  fecha date,
  cuadrilla text,
  estado text,
  tipo_trabajo text,
  numero_documento text,
  cliente text,
  sede text,
  codigo_pedido text,
  ticket text,
  codigo_liquidacion text,
  tipo_atencion text,
  tipo_partida text,
  tipo_partida_alterna text,
  archivo_ultima_carga text,
  usuario_ultima_carga text,
  fecha_ultima_actualizacion timestamp without time zone,
  imported_at timestamptz not null default now()
);

create index if not exists base_operativa_legacy_periodo_idx
  on public.base_operativa_legacy (periodo);
create index if not exists base_operativa_legacy_liquidacion_idx
  on public.base_operativa_legacy (codigo_liquidacion);
create index if not exists base_operativa_legacy_pedido_idx
  on public.base_operativa_legacy (codigo_pedido);
create index if not exists base_operativa_legacy_cuadrilla_fecha_idx
  on public.base_operativa_legacy (cuadrilla, fecha);

create table if not exists public.ajustes_partida_win (
  id text primary key,
  source_row integer not null unique,
  orden_id text not null,
  periodo text not null,
  fecha_orden timestamp without time zone,
  cuadrilla text,
  sede text,
  partida_win text,
  puntos_win numeric(12,3),
  partida_partner text,
  puntos_partner numeric(12,3),
  partida_propuesta text,
  puntos_propuesta numeric(12,3),
  origen_propuesta text,
  motivo text,
  estado text,
  solicitado_por text,
  fecha_solicitud timestamp without time zone,
  validado_por text,
  fecha_validacion timestamp without time zone,
  observacion text,
  imported_at timestamptz not null default now()
);

create index if not exists ajustes_partida_win_orden_idx
  on public.ajustes_partida_win (orden_id);
create index if not exists ajustes_partida_win_periodo_idx
  on public.ajustes_partida_win (periodo);
create index if not exists ajustes_partida_win_estado_idx
  on public.ajustes_partida_win (estado);

create table if not exists public.ajustes_orden_win (
  id text primary key,
  source_row integer not null unique,
  orden_id text not null,
  periodo text,
  fecha_orden timestamp without time zone,
  cuadrilla_win text,
  cuadrilla_efectiva text,
  sede_win text,
  origen text,
  motivo text,
  estado text,
  validado_por text,
  fecha_validacion timestamp without time zone,
  observacion text,
  imported_at timestamptz not null default now()
);

create index if not exists ajustes_orden_win_orden_idx
  on public.ajustes_orden_win (orden_id);

create table if not exists public.reglas_partida_win (
  id_regla text primary key,
  source_row integer not null unique,
  nivel text,
  tipo_traba_win text,
  motivo_finalizacion_win text,
  tipo_servicio_win text,
  producto_origen_win text,
  producto_servicio_win text,
  codigo_partida text,
  soporte_historico integer,
  pureza numeric(12,6),
  origen_aprendizaje text,
  periodo_entrenamiento text,
  estado text,
  vigencia_desde date,
  vigencia_hasta date,
  aplica_produccion text,
  requiere_revision text,
  observacion text,
  actualizado_por text,
  fecha_actualizacion timestamp without time zone,
  tipo_coincidencia_direccion text,
  patron_direccion text,
  patron_referencia text,
  clasificacion_ubicacion text,
  prioridad_regla integer,
  imported_at timestamptz not null default now()
);

create index if not exists reglas_partida_win_codigo_idx
  on public.reglas_partida_win (codigo_partida);
create index if not exists reglas_partida_win_estado_idx
  on public.reglas_partida_win (estado);

create table if not exists public.produccion_periodos (
  periodo text primary key,
  estado text not null,
  protegido boolean not null default false,
  motivo text,
  actualizado_por text,
  actualizado_at timestamptz not null default now(),
  constraint produccion_periodos_periodo_chk check (periodo ~ '^\d{4}-\d{2}$'),
  constraint produccion_periodos_estado_chk check (estado in ('CERRADO','PROTEGIDO','ACTIVO','PREPARACION'))
);

insert into public.produccion_periodos(periodo,estado,protegido,motivo,actualizado_por)
values
 ('2026-07','CERRADO',true,'Julio 2026 cerrado. No modificar salvo correccion expresa.','MIGRACION'),
 ('2026-08','PROTEGIDO',true,'Indicadores agosto protegidos durante migracion.','MIGRACION'),
 ('2026-09','ACTIVO',false,'Periodo operativo actual para pruebas de migracion.','MIGRACION')
on conflict (periodo) do nothing;

create or replace view public.mv_catalogo_puntaje_codigo as
select
  upper(trim(codigo)) as codigo,
  min(puntaje) as puntaje_min,
  max(puntaje) as puntaje_max,
  case when min(puntaje) = max(puntaje) then min(puntaje) else null end as puntaje_consistente,
  count(*)::integer as variantes,
  bool_and(upper(coalesce(estado_tarifa,''))='ACTIVO') as todas_activas
from public.catalogo_partidas_migracion
group by upper(trim(codigo));

create or replace view public.mv_produccion_legacy_resumen as
select
  p.periodo,
  count(*)::integer as filas,
  sum(p.cantidad) as cantidad,
  sum(case when c.puntaje_consistente is not null then p.cantidad*c.puntaje_consistente else 0 end) as puntos,
  count(*) filter (where c.codigo is null)::integer as filas_sin_catalogo,
  count(*) filter (where c.codigo is not null and c.puntaje_consistente is null)::integer as filas_puntaje_ambiguo
from public.produccion_legacy_snapshot p
left join public.mv_catalogo_puntaje_codigo c
  on c.codigo=upper(trim(p.codigo))
group by p.periodo;

create or replace view public.mv_ajuste_partida_vigente as
select distinct on (orden_id)
  *
from public.ajustes_partida_win
where upper(trim(coalesce(estado,'')))='VALIDADO'
order by orden_id, fecha_validacion desc nulls last, source_row desc;

alter table public.catalogo_partidas_migracion enable row level security;
alter table public.produccion_legacy_snapshot enable row level security;
alter table public.base_operativa_legacy enable row level security;
alter table public.ajustes_partida_win enable row level security;
alter table public.ajustes_orden_win enable row level security;
alter table public.reglas_partida_win enable row level security;
alter table public.produccion_periodos enable row level security;

revoke all on table public.catalogo_partidas_migracion from anon, authenticated;
revoke all on table public.produccion_legacy_snapshot from anon, authenticated;
revoke all on table public.base_operativa_legacy from anon, authenticated;
revoke all on table public.ajustes_partida_win from anon, authenticated;
revoke all on table public.ajustes_orden_win from anon, authenticated;
revoke all on table public.reglas_partida_win from anon, authenticated;
revoke all on table public.produccion_periodos from anon, authenticated;

commit;
