-- MI VISUAL - Dependencia minima GAR/VTR requerida por Produccion.
-- Solo snapshot de clasificacion; el modulo GAR/VTR completo se migra despues.

begin;

create table if not exists public.vtr_gar_clasificacion_legacy (
  id bigint generated by default as identity primary key,
  source_row integer not null unique,
  clave text,
  fecha_incidencia date,
  tipo text,
  ticket text,
  numero_documento text,
  cliente text,
  codigo_pedido text,
  codigo_liquidacion text,
  tipo_partida text,
  cuadrilla_ejecutora text,
  sede_ejecutora text,
  estado_calificacion text,
  cuadrilla_responsable text,
  sede_responsable text,
  calificado_por text,
  fecha_calificacion timestamp without time zone,
  observacion text,
  fecha_ultima_edicion timestamp without time zone,
  fecha_corte timestamp without time zone,
  periodo text,
  imported_at timestamptz not null default now()
);

create index if not exists vtr_gar_clasificacion_liq_idx
  on public.vtr_gar_clasificacion_legacy (codigo_liquidacion);
create index if not exists vtr_gar_clasificacion_ticket_idx
  on public.vtr_gar_clasificacion_legacy (ticket);
create index if not exists vtr_gar_clasificacion_estado_idx
  on public.vtr_gar_clasificacion_legacy (estado_calificacion);

alter table public.vtr_gar_clasificacion_legacy enable row level security;
revoke all on table public.vtr_gar_clasificacion_legacy from anon, authenticated;

create or replace view public.mv_vtr_gar_decision_por_orden as
select distinct on (codigo_liquidacion)
  codigo_liquidacion as orden_id,
  clave,
  tipo,
  ticket,
  estado_calificacion,
  cuadrilla_responsable,
  sede_responsable,
  calificado_por,
  fecha_calificacion,
  observacion,
  fecha_ultima_edicion
from public.vtr_gar_clasificacion_legacy
where nullif(trim(coalesce(codigo_liquidacion,'')),'') is not null
order by codigo_liquidacion, fecha_ultima_edicion desc nulls last, source_row desc;

commit;
