-- MI VISUAL - Produccion: puente de corte auditable
-- Preserva snapshot historico y registra correcciones explicitas.
-- No modifica Google Sheets ni Produccion productiva.

begin;

create table if not exists public.produccion_cortes_migracion (
  periodo text primary key,
  fecha_corte timestamp without time zone not null,
  fuente_snapshot text not null,
  cantidad_snapshot numeric(12,3) not null,
  puntos_snapshot numeric(14,3) not null,
  estado text not null default 'DIAGNOSTICO',
  observacion text,
  created_at timestamptz not null default now()
);

insert into public.produccion_cortes_migracion
(periodo,fecha_corte,fuente_snapshot,cantidad_snapshot,puntos_snapshot,estado,observacion)
values
('2026-09','2026-09-17 20:34:00','PRODUCCION_APP',1077,1920,'VALIDADO_MIGRACION',
 'Snapshot vigente usado para conciliacion. No recalcular historico publicado durante la migracion.')
on conflict (periodo) do update set
  fecha_corte=excluded.fecha_corte,
  fuente_snapshot=excluded.fuente_snapshot,
  cantidad_snapshot=excluded.cantidad_snapshot,
  puntos_snapshot=excluded.puntos_snapshot,
  estado=excluded.estado,
  observacion=excluded.observacion;

create table if not exists public.produccion_correcciones_migracion (
  id bigint generated by default as identity primary key,
  periodo text not null,
  orden_id text not null,
  accion text not null,
  codigo_partida text,
  puntos numeric(12,3),
  motivo text not null,
  fuente_validacion text,
  validado_por text,
  fecha_validacion timestamp without time zone,
  estado text not null default 'VALIDADA_MIGRACION',
  created_at timestamptz not null default now(),
  unique(periodo,orden_id,accion)
);

insert into public.produccion_correcciones_migracion
(periodo,orden_id,accion,codigo_partida,puntos,motivo,fuente_validacion,validado_por,fecha_validacion,estado)
values
('2026-09','3404829','RECUPERAR_PRODUCCION','PS',1,
 'Orden FINALIZADA con ticket VTR-47038979 clasificada por Jefatura como NO_ES_GAR_VTR; debe recuperar Produccion normal.',
 'BASE_VTR_GAR_DETECTADA','JEFZNORTE','2026-09-03 09:37:00','VALIDADA_MIGRACION')
on conflict (periodo,orden_id,accion) do update set
  codigo_partida=excluded.codigo_partida,
  puntos=excluded.puntos,
  motivo=excluded.motivo,
  fuente_validacion=excluded.fuente_validacion,
  validado_por=excluded.validado_por,
  fecha_validacion=excluded.fecha_validacion,
  estado=excluded.estado;

alter table public.produccion_cortes_migracion enable row level security;
alter table public.produccion_correcciones_migracion enable row level security;
revoke all on table public.produccion_cortes_migracion from anon,authenticated;
revoke all on table public.produccion_correcciones_migracion from anon,authenticated;
revoke all on sequence public.produccion_correcciones_migracion_id_seq from anon,authenticated;

create or replace view public.mv_produccion_conciliacion_corte_v1 as
with corr as (
  select
    periodo,
    count(*) filter(where estado='VALIDADA_MIGRACION' and accion='RECUPERAR_PRODUCCION')::numeric as cantidad_correccion,
    sum(case when estado='VALIDADA_MIGRACION' and accion='RECUPERAR_PRODUCCION' then coalesce(puntos,0) else 0 end) as puntos_correccion
  from public.produccion_correcciones_migracion
  group by periodo
),
motor as (
  select
    m.periodo_solicitud as periodo,
    count(*)::numeric as cantidad_motor,
    sum(coalesce(c.puntaje_consistente,0)) as puntos_motor,
    count(*) filter(where m.partida_motor is null)::integer as pendientes
  from public.mv_produccion_partida_motor_migracion_v1 m
  join public.produccion_cortes_migracion pc
    on pc.periodo=m.periodo_solicitud
  left join public.mv_catalogo_puntaje_codigo c
    on c.codigo=upper(trim(m.partida_motor))
  where m.elegible_produccion_efectiva
    and m.momento_ejecucion<=pc.fecha_corte
  group by m.periodo_solicitud
)
select
  pc.periodo,
  pc.fecha_corte,
  pc.cantidad_snapshot,
  pc.puntos_snapshot,
  coalesce(corr.cantidad_correccion,0) as cantidad_correccion,
  coalesce(corr.puntos_correccion,0) as puntos_correccion,
  pc.cantidad_snapshot+coalesce(corr.cantidad_correccion,0) as cantidad_objetivo_migracion,
  pc.puntos_snapshot+coalesce(corr.puntos_correccion,0) as puntos_objetivo_migracion,
  motor.cantidad_motor,
  motor.puntos_motor,
  motor.pendientes,
  motor.cantidad_motor-(pc.cantidad_snapshot+coalesce(corr.cantidad_correccion,0)) as diferencia_cantidad,
  motor.puntos_motor-(pc.puntos_snapshot+coalesce(corr.puntos_correccion,0)) as diferencia_puntos
from public.produccion_cortes_migracion pc
left join corr using(periodo)
left join motor using(periodo);

commit;
